license_callback({
  "MirOS": {
    "domain_content": true, 
    "domain_data": false, 
    "domain_software": true, 
    "family": "", 
    "id": "MirOS", 
    "is_okd_compliant": true, 
    "is_osi_compliant": true, 
    "maintainer": "", 
    "status": "active", 
    "title": "MirOS Licence (MirOS)", 
    "url": "http://www.opensource.org/licenses/MirOS"
  }, 
  "OGL-CA-2.0": {
    "domain_content": true, 
    "domain_data": true, 
    "domain_software": false, 
    "family": "", 
    "id": "OGL-CA-2.0", 
    "is_generic": false, 
    "is_okd_compliant": true, 
    "is_osi_compliant": false, 
    "maintainer": "Government of Canada", 
    "status": "active", 
    "title": "Open Government License 2.0 (Canada)", 
    "url": "http://data.gc.ca/eng/open-government-licence-canada"
  }, 
  "OGL-UK-2.0": {
    "domain_content": true, 
    "domain_data": true, 
    "domain_software": false, 
    "family": "", 
    "id": "OGL-UK-2.0", 
    "is_generic": false, 
    "is_okd_compliant": true, 
    "is_osi_compliant": false, 
    "maintainer": "UK Government", 
    "status": "active", 
    "title": "Open Government License 2.0 (United Kingdom)", 
    "url": "https://www.nationalarchives.gov.uk/doc/open-government-licence/version/2/"
  }, 
  "against-drm": {
    "domain_content": true, 
    "domain_data": false, 
    "domain_software": false, 
    "family": "", 
    "id": "against-drm", 
    "is_okd_compliant": true, 
    "is_osi_compliant": false, 
    "maintainer": "", 
    "status": "active", 
    "title": "Against DRM", 
    "url": "http://www.opendefinition.org/licenses/against-drm"
  }, 
  "cc-by": {
    "domain_content": true, 
    "domain_data": false, 
    "domain_software": false, 
    "family": "", 
    "id": "cc-by", 
    "is_okd_compliant": true, 
    "is_osi_compliant": false, 
    "maintainer": "Creative Commons", 
    "status": "active", 
    "title": "Creative Commons Attribution", 
    "url": "http://www.opendefinition.org/licenses/cc-by"
  }, 
  "cc-by-sa": {
    "domain_content": true, 
    "domain_data": false, 
    "domain_software": false, 
    "family": "", 
    "id": "cc-by-sa", 
    "is_okd_compliant": true, 
    "is_osi_compliant": false, 
    "maintainer": "Creative Commons", 
    "status": "active", 
    "title": "Creative Commons Attribution Share-Alike", 
    "url": "http://www.opendefinition.org/licenses/cc-by-sa"
  }, 
  "cc-nc": {
    "domain_content": false, 
    "domain_data": false, 
    "domain_software": false, 
    "family": "", 
    "id": "cc-nc", 
    "is_okd_compliant": false, 
    "is_osi_compliant": false, 
    "maintainer": "Creative Commons", 
    "status": "active", 
    "title": "Creative Commons Non-Commercial (Any)", 
    "url": "http://creativecommons.org/licenses/by-nc/2.0/"
  }, 
  "cc-zero": {
    "domain_content": true, 
    "domain_data": true, 
    "domain_software": true, 
    "family": "", 
    "id": "cc-zero", 
    "is_okd_compliant": true, 
    "is_osi_compliant": false, 
    "maintainer": "Creative Commons", 
    "status": "active", 
    "title": "Creative Commons CCZero", 
    "url": "http://www.opendefinition.org/licenses/cc-zero"
  }, 
  "dsl": {
    "domain_content": true, 
    "domain_data": false, 
    "domain_software": false, 
    "family": "", 
    "id": "dsl", 
    "is_okd_compliant": true, 
    "is_osi_compliant": false, 
    "maintainer": "", 
    "status": "active", 
    "title": "Design Science License", 
    "url": "http://www.opendefinition.org/licenses/dsl"
  }, 
  "fal": {
    "domain_content": true, 
    "domain_data": false, 
    "domain_software": false, 
    "family": "", 
    "id": "fal", 
    "is_okd_compliant": true, 
    "is_osi_compliant": false, 
    "maintainer": "", 
    "status": "active", 
    "title": "Free Art License", 
    "url": "http://www.opendefinition.org/licenses/fal"
  }, 
  "gfdl": {
    "domain_content": true, 
    "domain_data": false, 
    "domain_software": false, 
    "family": "", 
    "id": "gfdl", 
    "is_okd_compliant": true, 
    "is_osi_compliant": false, 
    "maintainer": "", 
    "status": "active", 
    "title": "GNU Free Documentation License", 
    "url": "http://www.opendefinition.org/licenses/gfdl"
  }, 
  "hesa-withrights": {
    "domain_content": true, 
    "domain_data": false, 
    "domain_software": false, 
    "family": "", 
    "id": "hesa-withrights", 
    "is_okd_compliant": true, 
    "is_osi_compliant": false, 
    "maintainer": "", 
    "status": "active", 
    "title": "Higher Education Statistics Agency Copyright with data.gov.uk rights", 
    "url": ""
  }, 
  "localauth-withrights": {
    "domain_content": true, 
    "domain_data": false, 
    "domain_software": false, 
    "family": "", 
    "id": "localauth-withrights", 
    "is_okd_compliant": true, 
    "is_osi_compliant": false, 
    "maintainer": "", 
    "status": "active", 
    "title": "Local Authority Copyright with data.gov.uk rights", 
    "url": ""
  }, 
  "notspecified": {
    "domain_content": false, 
    "domain_data": false, 
    "domain_software": false, 
    "family": "", 
    "id": "notspecified", 
    "is_generic": true, 
    "is_okd_compliant": false, 
    "is_osi_compliant": false, 
    "maintainer": "", 
    "status": "active", 
    "title": "License Not Specified", 
    "url": ""
  }, 
  "odc-by": {
    "domain_content": false, 
    "domain_data": true, 
    "domain_software": false, 
    "family": "", 
    "id": "odc-by", 
    "is_okd_compliant": true, 
    "is_osi_compliant": false, 
    "maintainer": "", 
    "status": "active", 
    "title": "Open Data Commons Attribution License", 
    "url": "http://www.opendefinition.org/licenses/odc-by"
  }, 
  "odc-odbl": {
    "domain_content": false, 
    "domain_data": true, 
    "domain_software": false, 
    "family": "", 
    "id": "odc-odbl", 
    "is_okd_compliant": true, 
    "is_osi_compliant": false, 
    "maintainer": "", 
    "status": "active", 
    "title": "Open Data Commons Open Database License (ODbL)", 
    "url": "http://www.opendefinition.org/licenses/odc-odbl"
  }, 
  "odc-pddl": {
    "domain_content": false, 
    "domain_data": true, 
    "domain_software": false, 
    "family": "", 
    "id": "odc-pddl", 
    "is_okd_compliant": true, 
    "is_osi_compliant": false, 
    "maintainer": "", 
    "status": "active", 
    "title": "Open Data Commons Public Domain Dedication and Licence (PDDL)", 
    "url": "http://www.opendefinition.org/licenses/odc-pddl"
  }, 
  "other-at": {
    "domain_content": true, 
    "domain_data": false, 
    "domain_software": false, 
    "family": "", 
    "id": "other-at", 
    "is_generic": true, 
    "is_okd_compliant": true, 
    "is_osi_compliant": false, 
    "maintainer": "", 
    "status": "active", 
    "title": "Other (Attribution)", 
    "url": ""
  }, 
  "other-closed": {
    "domain_content": false, 
    "domain_data": false, 
    "domain_software": false, 
    "family": "", 
    "id": "other-closed", 
    "is_generic": true, 
    "is_okd_compliant": false, 
    "is_osi_compliant": false, 
    "maintainer": "", 
    "status": "active", 
    "title": "Other (Not Open)", 
    "url": ""
  }, 
  "other-nc": {
    "domain_content": false, 
    "domain_data": false, 
    "domain_software": false, 
    "family": "", 
    "id": "other-nc", 
    "is_generic": true, 
    "is_okd_compliant": false, 
    "is_osi_compliant": false, 
    "maintainer": "", 
    "status": "active", 
    "title": "Other (Non-Commercial)", 
    "url": ""
  }, 
  "other-open": {
    "domain_content": true, 
    "domain_data": false, 
    "domain_software": false, 
    "family": "", 
    "id": "other-open", 
    "is_generic": true, 
    "is_okd_compliant": true, 
    "is_osi_compliant": false, 
    "maintainer": "", 
    "status": "active", 
    "title": "Other (Open)", 
    "url": ""
  }, 
  "other-pd": {
    "domain_content": true, 
    "domain_data": false, 
    "domain_software": false, 
    "family": "", 
    "id": "other-pd", 
    "is_generic": true, 
    "is_okd_compliant": true, 
    "is_osi_compliant": false, 
    "maintainer": "", 
    "status": "active", 
    "title": "Other (Public Domain)", 
    "url": ""
  }, 
  "tcl": {
    "domain_content": true, 
    "domain_data": false, 
    "domain_software": false, 
    "family": "", 
    "id": "tcl", 
    "is_okd_compliant": true, 
    "is_osi_compliant": false, 
    "maintainer": "", 
    "status": "active", 
    "title": "Talis Community License", 
    "url": "http://www.opendefinition.org/licenses/tcl"
  }, 
  "ukclickusepsi": {
    "domain_content": true, 
    "domain_data": false, 
    "domain_software": false, 
    "family": "", 
    "id": "ukclickusepsi", 
    "is_okd_compliant": true, 
    "is_osi_compliant": false, 
    "maintainer": "", 
    "status": "active", 
    "title": "UK Click Use PSI", 
    "url": ""
  }, 
  "ukcrown-withrights": {
    "domain_content": true, 
    "domain_data": false, 
    "domain_software": false, 
    "family": "", 
    "id": "ukcrown-withrights", 
    "is_okd_compliant": true, 
    "is_osi_compliant": false, 
    "maintainer": "", 
    "status": "active", 
    "title": "UK Crown Copyright with data.gov.uk rights", 
    "url": ""
  }, 
  "ukpsi": {
    "domain_content": true, 
    "domain_data": false, 
    "domain_software": false, 
    "family": "", 
    "id": "ukpsi", 
    "is_okd_compliant": true, 
    "is_osi_compliant": false, 
    "maintainer": "", 
    "status": "active", 
    "title": "UK PSI Public Sector Information", 
    "url": "http://www.opendefinition.org/licenses/ukpsi"
  }
});