license_callback({
  "AAL": {
    "domain_content": false,
    "domain_data": false,
    "domain_software": true,
    "family": "",
    "id": "AAL",
    "maintainer": "",
    "od_conformance": "not reviewed",
    "osd_conformance": "approved",
    "status": "active",
    "title": "Attribution Assurance Licenses",
    "url": "https://opensource.org/licenses/AAL"
  },
  "AFL-3.0": {
    "domain_content": true,
    "domain_data": false,
    "domain_software": true,
    "family": "",
    "id": "AFL-3.0",
    "maintainer": "Lawrence Rosen",
    "od_conformance": "not reviewed",
    "osd_conformance": "approved",
    "status": "active",
    "title": "Academic Free License 3.0",
    "url": "https://opensource.org/licenses/AFL-3.0"
  },
  "AGPL-3.0": {
    "domain_content": false,
    "domain_data": false,
    "domain_software": true,
    "family": "",
    "id": "AGPL-3.0",
    "legacy_ids": [
      "agpl-v3"
    ],
    "maintainer": "Free Software Foundation",
    "od_conformance": "not reviewed",
    "osd_conformance": "approved",
    "status": "active",
    "title": "GNU Affero General Public License v3",
    "url": "https://opensource.org/licenses/AGPL-3.0"
  },
  "APL-1.0": {
    "domain_content": false,
    "domain_data": false,
    "domain_software": true,
    "family": "",
    "id": "APL-1.0",
    "legacy_ids": [
      "apl1.0"
    ],
    "maintainer": "",
    "od_conformance": "not reviewed",
    "osd_conformance": "approved",
    "status": "active",
    "title": "Adaptive Public License 1.0",
    "url": "https://opensource.org/licenses/APL-1.0"
  },
  "APSL-2.0": {
    "domain_content": false,
    "domain_data": false,
    "domain_software": true,
    "family": "",
    "id": "APSL-2.0",
    "maintainer": "",
    "od_conformance": "not reviewed",
    "osd_conformance": "approved",
    "status": "active",
    "title": "Apple Public Source License 2.0",
    "url": "https://opensource.org/licenses/APSL-2.0"
  },
  "Apache-1.1": {
    "domain_content": false,
    "domain_data": false,
    "domain_software": true,
    "family": "",
    "id": "Apache-1.1",
    "maintainer": "Apache Foundation",
    "od_conformance": "not reviewed",
    "osd_conformance": "approved",
    "status": "retired",
    "title": "Apache Software License 1.1",
    "url": "https://opensource.org/licenses/Apache-1.1"
  },
  "Apache-2.0": {
    "domain_content": false,
    "domain_data": false,
    "domain_software": true,
    "family": "",
    "id": "Apache-2.0",
    "legacy_ids": [
      "apache2.0"
    ],
    "maintainer": "Apache Foundation",
    "od_conformance": "not reviewed",
    "osd_conformance": "approved",
    "status": "active",
    "title": "Apache Software License 2.0",
    "url": "https://opensource.org/licenses/Apache-2.0"
  },
  "Artistic-2.0": {
    "domain_content": false,
    "domain_data": false,
    "domain_software": true,
    "family": "",
    "id": "Artistic-2.0",
    "legacy_ids": [
      "artistic-license-2.0"
    ],
    "maintainer": "Perl Foundation",
    "od_conformance": "not reviewed",
    "osd_conformance": "approved",
    "status": "active",
    "title": "Artistic License 2.0",
    "url": "https://opensource.org/licenses/Artistic-2.0"
  },
  "BSD-2-Clause": {
    "domain_content": false,
    "domain_data": false,
    "domain_software": true,
    "family": "",
    "id": "BSD-2-Clause",
    "maintainer": "",
    "od_conformance": "not reviewed",
    "osd_conformance": "approved",
    "status": "active",
    "title": "BSD 2-Clause \"Simplified\" or \"FreeBSD\" License (BSD-2-Clause)",
    "url": "https://opensource.org/licenses/BSD-2-Clause"
  },
  "BSD-3-Clause": {
    "domain_content": false,
    "domain_data": false,
    "domain_software": true,
    "family": "",
    "id": "BSD-3-Clause",
    "maintainer": "",
    "od_conformance": "not reviewed",
    "osd_conformance": "approved",
    "status": "active",
    "title": "BSD 3-Clause \"New\" or \"Revised\" License (BSD-3-Clause)",
    "url": "https://opensource.org/licenses/BSD-3-Clause"
  },
  "BSL-1.0": {
    "domain_content": false,
    "domain_data": false,
    "domain_software": true,
    "family": "",
    "id": "BSL-1.0",
    "legacy_ids": [
      "bsl1.0"
    ],
    "maintainer": "",
    "od_conformance": "not reviewed",
    "osd_conformance": "approved",
    "status": "active",
    "title": "Boost Software License 1.0",
    "url": "https://opensource.org/licenses/BSL-1.0"
  },
  "CATOSL-1.1": {
    "domain_content": false,
    "domain_data": false,
    "domain_software": true,
    "family": "",
    "id": "CATOSL-1.1",
    "legacy_ids": [
      "ca-tosl1.1"
    ],
    "maintainer": "",
    "od_conformance": "not reviewed",
    "osd_conformance": "approved",
    "status": "active",
    "title": "Computer Associates Trusted Open Source License 1.1 (CATOSL-1.1)",
    "url": "https://opensource.org/licenses/CATOSL-1.1"
  },
  "CDDL-1.0": {
    "domain_content": false,
    "domain_data": false,
    "domain_software": true,
    "family": "",
    "id": "CDDL-1.0",
    "legacy_ids": [
      "cddl1"
    ],
    "maintainer": "",
    "od_conformance": "not reviewed",
    "osd_conformance": "approved",
    "status": "active",
    "title": "Common Development and Distribution License 1.0",
    "url": "https://opensource.org/licenses/CDDL-1.0"
  },
  "CECILL-2.1": {
    "domain_content": false,
    "domain_data": false,
    "domain_software": true,
    "family": "",
    "id": "CECILL-2.1",
    "maintainer": "",
    "od_conformance": "not reviewed",
    "osd_conformance": "approved",
    "status": "active",
    "title": "CeCILL License 2.1",
    "url": "https://opensource.org/licenses/CECILL-2.1"
  },
  "CNRI-Python": {
    "domain_content": false,
    "domain_data": false,
    "domain_software": true,
    "family": "",
    "id": "CNRI-Python",
    "maintainer": "",
    "od_conformance": "not reviewed",
    "osd_conformance": "approved",
    "status": "active",
    "title": "CNRI Python License",
    "url": "https://opensource.org/licenses/CNRI-Python"
  },
  "CPAL-1.0": {
    "domain_content": false,
    "domain_data": false,
    "domain_software": true,
    "family": "",
    "id": "CPAL-1.0",
    "legacy_ids": [
      "cpal_1.0"
    ],
    "maintainer": "",
    "od_conformance": "not reviewed",
    "osd_conformance": "approved",
    "status": "active",
    "title": "Common Public Attribution License 1.0",
    "url": "https://opensource.org/licenses/CPAL-1.0"
  },
  "CUA-OPL-1.0": {
    "domain_content": false,
    "domain_data": false,
    "domain_software": true,
    "family": "",
    "id": "CUA-OPL-1.0",
    "maintainer": "",
    "od_conformance": "not reviewed",
    "osd_conformance": "approved",
    "status": "active",
    "title": "CUA Office Public License 1.0",
    "url": "https://opensource.org/licenses/CUA-OPL-1.0"
  },
  "ECL-2.0": {
    "domain_content": false,
    "domain_data": false,
    "domain_software": true,
    "family": "",
    "id": "ECL-2.0",
    "legacy_ids": [
      "ecl2"
    ],
    "maintainer": "",
    "od_conformance": "not reviewed",
    "osd_conformance": "approved",
    "status": "active",
    "title": "Educational Community License 2.0",
    "url": "https://opensource.org/licenses/ECL-2.0"
  },
  "EFL-2.0": {
    "domain_content": false,
    "domain_data": false,
    "domain_software": true,
    "family": "",
    "id": "EFL-2.0",
    "maintainer": "",
    "od_conformance": "not reviewed",
    "osd_conformance": "approved",
    "status": "active",
    "title": "Eiffel Forum License 2.0",
    "url": "https://opensource.org/licenses/EFL-2.0"
  },
  "EPL-1.0": {
    "domain_content": false,
    "domain_data": false,
    "domain_software": true,
    "family": "",
    "id": "EPL-1.0",
    "legacy_ids": [
      "eclipse-1.0"
    ],
    "maintainer": "Eclipse Foundation",
    "od_conformance": "not reviewed",
    "osd_conformance": "approved",
    "status": "active",
    "title": "Eclipse Public License 1.0",
    "url": "https://opensource.org/licenses/EPL-1.0"
  },
  "EUDatagrid": {
    "domain_content": false,
    "domain_data": false,
    "domain_software": true,
    "family": "",
    "id": "EUDatagrid",
    "maintainer": "",
    "od_conformance": "not reviewed",
    "osd_conformance": "approved",
    "status": "active",
    "title": "EU DataGrid Software License",
    "url": "https://opensource.org/licenses/EUDatagrid"
  },
  "EUPL-1.1": {
    "domain_content": false,
    "domain_data": false,
    "domain_software": true,
    "family": "",
    "id": "EUPL-1.1",
    "maintainer": "",
    "od_conformance": "not reviewed",
    "osd_conformance": "approved",
    "status": "active",
    "title": "European Union Public License 1.1",
    "url": "https://opensource.org/licenses/EUPL-1.1"
  },
  "Entessa": {
    "domain_content": false,
    "domain_data": false,
    "domain_software": true,
    "family": "",
    "id": "Entessa",
    "maintainer": "",
    "od_conformance": "not reviewed",
    "osd_conformance": "approved",
    "status": "active",
    "title": "Entessa Public License",
    "url": "https://opensource.org/licenses/Entessa"
  },
  "Fair": {
    "domain_content": false,
    "domain_data": false,
    "domain_software": true,
    "family": "",
    "id": "Fair",
    "maintainer": "",
    "od_conformance": "not reviewed",
    "osd_conformance": "approved",
    "status": "active",
    "title": "Fair License",
    "url": "https://opensource.org/licenses/Fair"
  },
  "Frameworx-1.0": {
    "domain_content": false,
    "domain_data": false,
    "domain_software": true,
    "family": "",
    "id": "Frameworx-1.0",
    "maintainer": "",
    "od_conformance": "not reviewed",
    "osd_conformance": "approved",
    "status": "active",
    "title": "Frameworx License 1.0",
    "url": "https://opensource.org/licenses/Frameworx-1.0"
  },
  "GPL-2.0": {
    "domain_content": false,
    "domain_data": false,
    "domain_software": true,
    "family": "",
    "id": "GPL-2.0",
    "maintainer": "Free Software Foundation",
    "od_conformance": "not reviewed",
    "osd_conformance": "approved",
    "status": "active",
    "title": "GNU General Public License 2.0",
    "url": "https://opensource.org/licenses/GPL-2.0"
  },
  "GPL-3.0": {
    "domain_content": false,
    "domain_data": false,
    "domain_software": true,
    "family": "",
    "id": "GPL-3.0",
    "maintainer": "Free Software Foundation",
    "od_conformance": "not reviewed",
    "osd_conformance": "approved",
    "status": "active",
    "title": "GNU General Public License 3.0",
    "url": "https://opensource.org/licenses/GPL-3.0"
  },
  "HPND": {
    "domain_content": false,
    "domain_data": false,
    "domain_software": true,
    "family": "",
    "id": "HPND",
    "maintainer": "",
    "od_conformance": "not reviewed",
    "osd_conformance": "approved",
    "status": "active",
    "title": "Historical Permission Notice and Disclaimer",
    "url": "https://opensource.org/licenses/HPND"
  },
  "IPA": {
    "domain_content": false,
    "domain_data": false,
    "domain_software": true,
    "family": "",
    "id": "IPA",
    "maintainer": "",
    "od_conformance": "not reviewed",
    "osd_conformance": "approved",
    "status": "active",
    "title": "IPA Font License",
    "url": "https://opensource.org/licenses/IPA"
  },
  "IPL-1.0": {
    "domain_content": false,
    "domain_data": false,
    "domain_software": true,
    "family": "",
    "id": "IPL-1.0",
    "legacy_ids": [
      "ibmpl"
    ],
    "maintainer": "IBM Corporation",
    "od_conformance": "not reviewed",
    "osd_conformance": "approved",
    "status": "active",
    "title": "IBM Public License 1.0",
    "url": "https://opensource.org/licenses/IPL-1.0"
  },
  "ISC": {
    "domain_content": false,
    "domain_data": false,
    "domain_software": true,
    "family": "",
    "id": "ISC",
    "legacy_ids": [
      "isc-license"
    ],
    "maintainer": "",
    "od_conformance": "not reviewed",
    "osd_conformance": "approved",
    "status": "active",
    "title": "ISC License",
    "url": "https://opensource.org/licenses/ISC"
  },
  "Intel": {
    "domain_content": false,
    "domain_data": false,
    "domain_software": true,
    "family": "",
    "id": "Intel",
    "legacy_ids": [
      "intel-osl"
    ],
    "maintainer": "Intel Corporation",
    "od_conformance": "not reviewed",
    "osd_conformance": "approved",
    "status": "retired",
    "title": "Intel Open Source License",
    "url": "https://opensource.org/licenses/Intel"
  },
  "LGPL-2.1": {
    "domain_content": false,
    "domain_data": false,
    "domain_software": true,
    "family": "",
    "id": "LGPL-2.1",
    "maintainer": "Free Software Foundation",
    "od_conformance": "not reviewed",
    "osd_conformance": "approved",
    "status": "active",
    "title": "GNU Lesser General Public License 2.1",
    "url": "https://opensource.org/licenses/LGPL-2.1"
  },
  "LGPL-3.0": {
    "domain_content": false,
    "domain_data": false,
    "domain_software": true,
    "family": "",
    "id": "LGPL-3.0",
    "maintainer": "Free Software Foundation",
    "od_conformance": "not reviewed",
    "osd_conformance": "approved",
    "status": "active",
    "title": "GNU Lesser General Public License 3.0",
    "url": "https://opensource.org/licenses/LGPL-3.0"
  },
  "LPL-1.0": {
    "domain_content": false,
    "domain_data": false,
    "domain_software": true,
    "family": "",
    "id": "LPL-1.0",
    "maintainer": "",
    "od_conformance": "not reviewed",
    "osd_conformance": "approved",
    "status": "retired",
    "title": "Lucent Public License (\"Plan9\") 1.0",
    "url": "https://opensource.org/licenses/LPL-1.0"
  },
  "LPL-1.02": {
    "domain_content": false,
    "domain_data": false,
    "domain_software": true,
    "family": "",
    "id": "LPL-1.02",
    "maintainer": "",
    "od_conformance": "not reviewed",
    "osd_conformance": "approved",
    "status": "active",
    "title": "Lucent Public License 1.02",
    "url": "https://opensource.org/licenses/LPL-1.02"
  },
  "LPPL-1.3c": {
    "domain_content": false,
    "domain_data": false,
    "domain_software": true,
    "family": "",
    "id": "LPPL-1.3c",
    "maintainer": "",
    "od_conformance": "not reviewed",
    "osd_conformance": "approved",
    "status": "active",
    "title": "LaTeX Project Public License 1.3c",
    "url": "https://opensource.org/licenses/LPPL-1.3c"
  },
  "MIT": {
    "domain_content": false,
    "domain_data": false,
    "domain_software": true,
    "family": "",
    "id": "MIT",
    "legacy_ids": [
      "mit-license"
    ],
    "maintainer": "",
    "od_conformance": "not reviewed",
    "osd_conformance": "approved",
    "status": "active",
    "title": "MIT License",
    "url": "https://opensource.org/licenses/MIT"
  },
  "MPL-1.0": {
    "domain_content": false,
    "domain_data": false,
    "domain_software": true,
    "family": "",
    "id": "MPL-1.0",
    "maintainer": "Mozilla Foundation",
    "od_conformance": "not reviewed",
    "osd_conformance": "approved",
    "status": "retired",
    "title": "Mozilla Public License 1.0",
    "url": "https://opensource.org/licenses/MPL-1.0"
  },
  "MPL-1.1": {
    "domain_content": false,
    "domain_data": false,
    "domain_software": true,
    "family": "",
    "id": "MPL-1.1",
    "legacy_ids": [
      "mozilla1.1"
    ],
    "maintainer": "Mozilla Foundation",
    "od_conformance": "not reviewed",
    "osd_conformance": "approved",
    "status": "retired",
    "title": "Mozilla Public License 1.1",
    "url": "https://opensource.org/licenses/MPL-1.1"
  },
  "MPL-2.0": {
    "domain_content": false,
    "domain_data": false,
    "domain_software": true,
    "family": "",
    "id": "MPL-2.0",
    "legacy_ids": [
      "mozilla2.0"
    ],
    "maintainer": "Mozilla Foundation",
    "od_conformance": "not reviewed",
    "osd_conformance": "approved",
    "status": "active",
    "title": "Mozilla Public License 2.0",
    "url": "https://opensource.org/licenses/MPL-2.0"
  },
  "MS-PL": {
    "domain_content": false,
    "domain_data": false,
    "domain_software": true,
    "family": "",
    "id": "MS-PL",
    "maintainer": "Microsoft Corporation",
    "od_conformance": "not reviewed",
    "osd_conformance": "approved",
    "status": "active",
    "title": "Microsoft Public License",
    "url": "https://opensource.org/licenses/MS-PL"
  },
  "MS-RL": {
    "domain_content": false,
    "domain_data": false,
    "domain_software": true,
    "family": "",
    "id": "MS-RL",
    "maintainer": "Microsoft Corporation",
    "od_conformance": "not reviewed",
    "osd_conformance": "approved",
    "status": "active",
    "title": "Microsoft Reciprocal License",
    "url": "https://opensource.org/licenses/MS-RL"
  },
  "MirOS": {
    "domain_content": true,
    "domain_data": false,
    "domain_software": true,
    "family": "",
    "id": "MirOS",
    "maintainer": "",
    "od_conformance": "approved",
    "osd_conformance": "approved",
    "status": "active",
    "title": "MirOS Licence",
    "url": "https://opensource.org/licenses/MirOS"
  },
  "Motosoto": {
    "domain_content": false,
    "domain_data": false,
    "domain_software": true,
    "family": "",
    "id": "Motosoto",
    "maintainer": "",
    "od_conformance": "not reviewed",
    "osd_conformance": "approved",
    "status": "active",
    "title": "Motosoto License",
    "url": "https://opensource.org/licenses/Motosoto"
  },
  "Multics": {
    "domain_content": false,
    "domain_data": false,
    "domain_software": true,
    "family": "",
    "id": "Multics",
    "maintainer": "",
    "od_conformance": "not reviewed",
    "osd_conformance": "approved",
    "status": "active",
    "title": "Multics License",
    "url": "https://opensource.org/licenses/Multics"
  },
  "NASA-1.3": {
    "domain_content": false,
    "domain_data": false,
    "domain_software": true,
    "family": "",
    "id": "NASA-1.3",
    "legacy_ids": [
      "nasa1.3"
    ],
    "maintainer": "",
    "od_conformance": "not reviewed",
    "osd_conformance": "approved",
    "status": "active",
    "title": "NASA Open Source Agreement 1.3",
    "url": "https://opensource.org/licenses/NASA-1.3"
  },
  "NCSA": {
    "domain_content": false,
    "domain_data": false,
    "domain_software": true,
    "family": "",
    "id": "NCSA",
    "legacy_ids": [
      "uoi-ncsa"
    ],
    "maintainer": "",
    "od_conformance": "not reviewed",
    "osd_conformance": "approved",
    "status": "active",
    "title": "University of Illinois/NCSA Open Source License",
    "url": "https://opensource.org/licenses/NCSA"
  },
  "NGPL": {
    "domain_content": false,
    "domain_data": false,
    "domain_software": true,
    "family": "",
    "id": "NGPL",
    "maintainer": "",
    "od_conformance": "not reviewed",
    "osd_conformance": "approved",
    "status": "active",
    "title": "Nethack General Public License",
    "url": "https://opensource.org/licenses/NGPL"
  },
  "NPOSL-3.0": {
    "domain_content": true,
    "domain_data": false,
    "domain_software": true,
    "family": "",
    "id": "NPOSL-3.0",
    "legacy_ids": [
      "nosl3.0"
    ],
    "maintainer": "Lawrence Rosen",
    "od_conformance": "not reviewed",
    "osd_conformance": "approved",
    "status": "active",
    "title": "Non-Profit Open Software License 3.0",
    "url": "https://opensource.org/licenses/NPOSL-3.0"
  },
  "NTP": {
    "domain_content": false,
    "domain_data": false,
    "domain_software": true,
    "family": "",
    "id": "NTP",
    "maintainer": "",
    "od_conformance": "not reviewed",
    "osd_conformance": "approved",
    "status": "active",
    "title": "NTP License",
    "url": "https://opensource.org/licenses/NTP"
  },
  "Naumen": {
    "domain_content": false,
    "domain_data": false,
    "domain_software": true,
    "family": "",
    "id": "Naumen",
    "maintainer": "",
    "od_conformance": "not reviewed",
    "osd_conformance": "approved",
    "status": "active",
    "title": "Naumen Public License",
    "url": "https://opensource.org/licenses/Naumen"
  },
  "Nokia": {
    "domain_content": false,
    "domain_data": false,
    "domain_software": true,
    "family": "",
    "id": "Nokia",
    "maintainer": "",
    "od_conformance": "not reviewed",
    "osd_conformance": "approved",
    "status": "active",
    "title": "Nokia Open Source License",
    "url": "https://opensource.org/licenses/Nokia"
  },
  "OCLC-2.0": {
    "domain_content": false,
    "domain_data": false,
    "domain_software": true,
    "family": "",
    "id": "OCLC-2.0",
    "legacy_ids": [
      "oclc2"
    ],
    "maintainer": "",
    "od_conformance": "not reviewed",
    "osd_conformance": "approved",
    "status": "active",
    "title": "OCLC Research Public License 2.0",
    "url": "https://opensource.org/licenses/OCLC-2.0"
  },
  "OFL-1.1": {
    "domain_content": false,
    "domain_data": false,
    "domain_software": true,
    "family": "",
    "id": "OFL-1.1",
    "maintainer": "",
    "od_conformance": "not reviewed",
    "osd_conformance": "approved",
    "status": "active",
    "title": "Open Font License 1.1",
    "url": "https://opensource.org/licenses/OFL-1.1"
  },
  "OGTSL": {
    "domain_content": false,
    "domain_data": false,
    "domain_software": true,
    "family": "",
    "id": "OGTSL",
    "maintainer": "",
    "od_conformance": "not reviewed",
    "osd_conformance": "approved",
    "status": "active",
    "title": "Open Group Test Suite License",
    "url": "https://opensource.org/licenses/OGTSL"
  },
  "OSL-3.0": {
    "domain_content": true,
    "domain_data": false,
    "domain_software": true,
    "family": "",
    "id": "OSL-3.0",
    "maintainer": "Lawrence Rosen",
    "od_conformance": "not reviewed",
    "osd_conformance": "approved",
    "status": "active",
    "title": "Open Software License 3.0",
    "url": "https://opensource.org/licenses/OSL-3.0"
  },
  "PHP-3.0": {
    "domain_content": false,
    "domain_data": false,
    "domain_software": true,
    "family": "",
    "id": "PHP-3.0",
    "maintainer": "PHP Group",
    "od_conformance": "not reviewed",
    "osd_conformance": "approved",
    "status": "active",
    "title": "PHP License 3.0",
    "url": "https://opensource.org/licenses/PHP-3.0"
  },
  "PostgreSQL": {
    "domain_content": false,
    "domain_data": false,
    "domain_software": true,
    "family": "",
    "id": "PostgreSQL",
    "maintainer": "PostgreSQL Global Development Group",
    "od_conformance": "not reviewed",
    "osd_conformance": "approved",
    "status": "active",
    "title": "PostgreSQL License",
    "url": "https://opensource.org/licenses/PostgreSQL"
  },
  "Python-2.0": {
    "domain_content": false,
    "domain_data": false,
    "domain_software": true,
    "family": "",
    "id": "Python-2.0",
    "maintainer": "",
    "od_conformance": "not reviewed",
    "osd_conformance": "approved",
    "status": "active",
    "title": "Python License 2.0",
    "url": "https://opensource.org/licenses/Python-2.0"
  },
  "QPL-1.0": {
    "domain_content": false,
    "domain_data": false,
    "domain_software": true,
    "family": "",
    "id": "QPL-1.0",
    "maintainer": "",
    "od_conformance": "not reviewed",
    "osd_conformance": "approved",
    "status": "active",
    "title": "Q Public License 1.0",
    "url": "https://opensource.org/licenses/QPL-1.0"
  },
  "RPL-1.5": {
    "domain_content": false,
    "domain_data": false,
    "domain_software": true,
    "family": "",
    "id": "RPL-1.5",
    "maintainer": "",
    "od_conformance": "not reviewed",
    "osd_conformance": "approved",
    "status": "active",
    "title": "Reciprocal Public License 1.5",
    "url": "https://opensource.org/licenses/RPL-1.5"
  },
  "RPSL-1.0": {
    "domain_content": false,
    "domain_data": false,
    "domain_software": true,
    "family": "",
    "id": "RPSL-1.0",
    "maintainer": "",
    "od_conformance": "not reviewed",
    "osd_conformance": "approved",
    "status": "active",
    "title": "RealNetworks Public Source License 1.0",
    "url": "https://opensource.org/licenses/RPSL-1.0"
  },
  "RSCPL": {
    "domain_content": false,
    "domain_data": false,
    "domain_software": true,
    "family": "",
    "id": "RSCPL",
    "maintainer": "",
    "od_conformance": "not reviewed",
    "osd_conformance": "approved",
    "status": "active",
    "title": "Ricoh Source Code Public License",
    "url": "https://opensource.org/licenses/RSCPL"
  },
  "SISSL": {
    "domain_content": false,
    "domain_data": false,
    "domain_software": true,
    "family": "",
    "id": "SISSL",
    "legacy_ids": [
      "sun-issl"
    ],
    "maintainer": "",
    "od_conformance": "not reviewed",
    "osd_conformance": "approved",
    "status": "retired",
    "title": "Sun Industry Standards Source License 1.1",
    "url": "https://opensource.org/licenses/SISSL"
  },
  "SPL-1.0": {
    "domain_content": false,
    "domain_data": false,
    "domain_software": true,
    "family": "",
    "id": "SPL-1.0",
    "maintainer": "",
    "od_conformance": "not reviewed",
    "osd_conformance": "approved",
    "status": "active",
    "title": "Sun Public License 1.0",
    "url": "https://opensource.org/licenses/SPL-1.0"
  },
  "SimPL-2.0": {
    "domain_content": false,
    "domain_data": false,
    "domain_software": true,
    "family": "",
    "id": "SimPL-2.0",
    "maintainer": "",
    "od_conformance": "not reviewed",
    "osd_conformance": "approved",
    "status": "active",
    "title": "Simple Public License 2.0",
    "url": "https://opensource.org/licenses/SimPL-2.0"
  },
  "Sleepycat": {
    "domain_content": false,
    "domain_data": false,
    "domain_software": true,
    "family": "",
    "id": "Sleepycat",
    "maintainer": "Oracle Corporation",
    "od_conformance": "not reviewed",
    "osd_conformance": "approved",
    "status": "active",
    "title": "Sleepycat License",
    "url": "https://opensource.org/licenses/Sleepycat"
  },
  "VSL-1.0": {
    "domain_content": false,
    "domain_data": false,
    "domain_software": true,
    "family": "",
    "id": "VSL-1.0",
    "maintainer": "",
    "od_conformance": "not reviewed",
    "osd_conformance": "approved",
    "status": "active",
    "title": "Vovida Software License 1.0",
    "url": "https://opensource.org/licenses/VSL-1.0"
  },
  "W3C": {
    "domain_content": false,
    "domain_data": false,
    "domain_software": true,
    "family": "",
    "id": "W3C",
    "maintainer": "World Wide Web Consortium",
    "od_conformance": "not reviewed",
    "osd_conformance": "approved",
    "status": "active",
    "title": "W3C License",
    "url": "https://opensource.org/licenses/W3C"
  },
  "WXwindows": {
    "domain_content": false,
    "domain_data": false,
    "domain_software": true,
    "family": "",
    "id": "WXwindows",
    "maintainer": "wxWidgets Team",
    "od_conformance": "not reviewed",
    "osd_conformance": "approved",
    "status": "active",
    "title": "wxWindows Library License",
    "url": "https://opensource.org/licenses/WXwindows"
  },
  "Watcom-1.0": {
    "domain_content": false,
    "domain_data": false,
    "domain_software": true,
    "family": "",
    "id": "Watcom-1.0",
    "maintainer": "",
    "od_conformance": "not reviewed",
    "osd_conformance": "approved",
    "status": "active",
    "title": "Sybase Open Watcom Public License 1.0",
    "url": "https://opensource.org/licenses/Watcom-1.0"
  },
  "Xnet": {
    "domain_content": false,
    "domain_data": false,
    "domain_software": true,
    "family": "",
    "id": "Xnet",
    "maintainer": "",
    "od_conformance": "not reviewed",
    "osd_conformance": "approved",
    "status": "active",
    "title": "X.Net License",
    "url": "https://opensource.org/licenses/Xnet"
  },
  "ZPL-2.0": {
    "domain_content": false,
    "domain_data": false,
    "domain_software": true,
    "family": "",
    "id": "ZPL-2.0",
    "maintainer": "Zope Foundation",
    "od_conformance": "not reviewed",
    "osd_conformance": "approved",
    "status": "active",
    "title": "Zope Public License 2.0",
    "url": "https://opensource.org/licenses/ZPL-2.0"
  },
  "Zlib": {
    "domain_content": false,
    "domain_data": false,
    "domain_software": true,
    "family": "",
    "id": "Zlib",
    "legacy_ids": [
      "zlib-license"
    ],
    "maintainer": "",
    "od_conformance": "not reviewed",
    "osd_conformance": "approved",
    "status": "active",
    "title": "zlib/libpng license",
    "url": "https://opensource.org/licenses/Zlib"
  },
  "mitre": {
    "domain_content": false,
    "domain_data": false,
    "domain_software": true,
    "family": "",
    "id": "mitre",
    "maintainer": "",
    "od_conformance": "not reviewed",
    "osd_conformance": "approved",
    "status": "active",
    "title": "MITRE Collaborative Virtual Workspace License (CVW License)",
    "url": "https://opensource.org/licenses/CVW"
  }
});